{{- range $app := .Values.appRoots }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $app }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - {{ $.Values.repoUrl }}
{{- end }}
